// <auto-generated />
using System;
using CRUD_Operation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Operation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250518073241_ScriptAddingMasterDataForMoreTesting")]
    partial class ScriptAddingMasterDataForMoreTesting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("CRUD_Operation.Data.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18baeb8a-362d-4576-8da2-d836d5abe2c4"),
                            Description = "Testing the data insertion on time of Creation i.e Master data",
                            DueDate = new DateTime(2025, 5, 18, 13, 2, 40, 887, DateTimeKind.Local).AddTicks(2852),
                            IsComplete = true,
                            Title = "Test Task"
                        },
                        new
                        {
                            Id = new Guid("85222b55-996a-4c1b-9d97-f12fd749244a"),
                            Description = "task 2 for testing getall api",
                            DueDate = new DateTime(2025, 5, 18, 13, 2, 40, 887, DateTimeKind.Local).AddTicks(2907),
                            IsComplete = true,
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = new Guid("c9eae515-631e-4680-89c0-6ad5d28c423e"),
                            Description = "task 3 for testing getbyID api",
                            DueDate = new DateTime(2025, 5, 18, 13, 2, 40, 887, DateTimeKind.Local).AddTicks(2910),
                            IsComplete = true,
                            Title = "Task3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
